/**
 * Test Data Seeding Utility
 * Generates 6 tapes, 6 recordings, and 6 documents for testing
 */

export const SEED_TAPES = [
  {
    tape_id: 'TAPE-001',
    title: 'MASCOT MALFUNCTION INCIDENT — SECTOR 3',
    date: '1947-06-15',
    length: '47:32',
    status: 'CORRUPTED',
    is_corrupt: true,
    is_visible: true,
    sort_order: 1,
    notes: 'Audio degradation begins at 18:45. Subject becomes unintelligible.',
  },
  {
    tape_id: 'TAPE-002',
    title: 'LATE NIGHT SURVEILLANCE — MAINTENANCE TUNNEL B',
    date: '1947-07-03',
    length: '1:23:15',
    status: 'SAFE',
    is_corrupt: false,
    is_visible: true,
    sort_order: 2,
    notes: 'Recovered from forgotten storage. Quality surprisingly intact.',
  },
  {
    tape_id: 'TAPE-003',
    title: 'STAFF DEBRIEFING — CLASSIFIED',
    date: '1947-08-01',
    length: '33:47',
    status: 'REDACTED',
    is_corrupt: false,
    is_visible: true,
    sort_order: 3,
    notes: 'Large sections removed during archival process.',
  },
  {
    tape_id: 'TAPE-004',
    title: 'THERMAL INCIDENT DOCUMENTATION',
    date: '1947-09-12',
    length: '12:06',
    status: 'CORRUPT',
    is_corrupt: true,
    is_visible: true,
    sort_order: 4,
    notes: 'Heat damage to magnetic tape. Reconstruction attempted.',
  },
  {
    tape_id: 'TAPE-005',
    title: 'FINAL SHUTDOWN SEQUENCE — PARK CLOSURE',
    date: '1947-10-31',
    length: '2:18:45',
    status: 'SEALED',
    is_corrupt: false,
    is_visible: true,
    sort_order: 5,
    notes: 'Complete record of decommissioning procedures.',
  },
  {
    tape_id: 'TAPE-006',
    title: 'UNKNOWN ORIGIN — FOUND IN WALL CAVITY',
    date: '1947-07-22',
    length: '14:28:33',
    status: 'UNKNOWN',
    is_corrupt: true,
    is_visible: true,
    sort_order: 6,
    notes: 'Date and provenance unconfirmed. Handle with extreme caution.',
  },
];

export const SEED_RECORDINGS = [
  {
    recording_id: 'REC-001',
    title: 'FLORA UNIT — ACTIVATION TEST',
    description: 'Initial voice box diagnostic. Primary vocalization patterns.',
    duration: '3:42',
    date: '1947-05-01',
    status: 'DECLASSIFIED',
    is_visible: true,
    sort_order: 1,
  },
  {
    recording_id: 'REC-002',
    title: 'MECHANICAL FAILURE — AUDIO LOG',
    description: 'Progressive servo motor degradation captured in real-time.',
    duration: '8:15',
    date: '1947-06-20',
    status: 'INTERCEPTED',
    is_visible: true,
    sort_order: 2,
  },
  {
    recording_id: 'REC-003',
    title: 'STAFF EVACUATION PROCEDURES',
    description: 'Emergency broadcast from park management system.',
    duration: '2:31',
    date: '1947-08-15',
    status: 'DECLASSIFIED',
    is_visible: true,
    sort_order: 3,
  },
  {
    recording_id: 'REC-004',
    title: 'PSYCHOACOUSTIC ANALYSIS — CORRUPTED',
    description: 'Attempted categorization of anomalous audio patterns.',
    duration: '15:47',
    date: '1947-09-01',
    status: 'CORRUPTED',
    is_visible: true,
    sort_order: 4,
  },
  {
    recording_id: 'REC-005',
    title: 'MORSE CODE TRANSMISSION — UNKNOWN ORIGIN',
    description: 'Rhythmic pattern detected in electromagnetic noise floor.',
    duration: '11:23',
    date: '1947-10-10',
    status: 'INTERCEPTED',
    is_visible: true,
    sort_order: 5,
  },
  {
    recording_id: 'REC-006',
    title: 'FINAL HOUR — PARK CLOSURE AMBIENT',
    description: 'Environmental audio during last recorded operational day.',
    duration: '5:56',
    date: '1947-10-31',
    status: 'DECLASSIFIED',
    is_visible: true,
    sort_order: 6,
  },
];

export const SEED_DOCUMENTS = [
  {
    document_id: 'DOC-001',
    title: 'INCIDENT REPORT — INITIAL ASSESSMENT',
    content: 'MASCOT UNIT MALFUNCTION — FLORA UNIT EXHIBIT\n\nDate: June 15, 1947\nLocation: Entertainment Theater, Sector 3\nPersonnel Present: 3 staff members, 47 guests\n\nAt 19:47, FLORA unit exhibited unexpected behavioral deviation. Vocalizations became incomprehensible. Movement patterns exceeded programmed parameters. Security was notified. Guest area evacuated immediately.\n\nInitial assessment suggests electrical feedback or mechanical failure. Further investigation required.',
    doc_type: 'report',
    date: '1947-06-16',
    status: 'CLASSIFIED',
    is_visible: true,
    sort_order: 1,
  },
  {
    document_id: 'DOC-002',
    title: 'MAINTENANCE LOG — FLORA UNIT (PARTIAL)',
    content: 'MAINTENANCE RECORDS — FLORA ANIMATRONIC UNIT\n\n1947-05-15: Standard operational check. All systems nominal.\n1947-06-01: Servo recalibration performed. Voice modulation unit tested successfully.\n1947-06-14: Unusual electromagnetic readings detected. Source unclear.\n1947-06-15: [CRITICAL INCIDENT — DETAILS REDACTED] INCIDENT OCCURRED\n1947-06-16: Unit placed in secure storage pending investigation.',
    doc_type: 'log',
    date: '1947-06-20',
    status: 'CLASSIFIED',
    is_visible: true,
    sort_order: 2,
  },
  {
    document_id: 'DOC-003',
    title: 'STAFF TESTIMONY — WITNESS ACCOUNTS',
    content: 'TESTIMONY COMPILATION\n\nWitness A (Security Chief):\n"I heard the screaming first. The audio wasn\'t... synchronized with the mouth movements. It was like two different things were speaking at once."\n\nWitness B (Technician):\n"The power draw spiked to impossible levels. It would have melted the circuits. But the temperature readings never changed."\n\nWitness C (Park Director):\n"We shut it down. But I don\'t think it turned off. I think it... stopped playing along."',
    doc_type: 'testimony',
    date: '1947-06-20',
    status: 'CLASSIFIED',
    is_visible: true,
    sort_order: 3,
  },
  {
    document_id: 'DOC-004',
    title: 'THERMAL INCIDENT ANALYSIS — PYRO UNIT',
    content: 'INCIDENT REPORT — PYRO UNIT THERMAL FAILURE\n\nDate: September 12, 1947\nIncident Type: Uncontrolled thermal event\nLocation: Costume storage facility\n\nPYRO unit costume was discovered ablaze in secure storage. Fire occurred despite:\n- Unit being powered down\n- Fire suppression systems in place\n- No external ignition source detected\n\nThe costume was destroyed. The occupant was not found. Investigation suggests human operator was still inside the suit during storage. No remains recovered.',
    doc_type: 'report',
    date: '1947-09-15',
    status: 'CLASSIFIED',
    is_visible: true,
    sort_order: 4,
  },
  {
    document_id: 'DOC-005',
    title: 'CLOSURE DECISION — EXECUTIVE SUMMARY',
    content: 'EXECUTIVE DECISION — PARK CLOSURE\n\nFollowing incidents in June, August, and September, the decision has been made to permanently close Mascot Park effective October 31, 1947.\n\nOfficial cause: Economic downturn post-war\nActual cause: [REDACTED]\n\nAll units to be dismantled and secured. Records to be archived into deepest storage. Staff to sign NDAs. Public will be told the park "burned down."\n\nThis decision is final and non-negotiable.',
    doc_type: 'directive',
    date: '1947-10-20',
    status: 'CLASSIFIED',
    is_visible: true,
    sort_order: 5,
  },
  {
    document_id: 'DOC-006',
    title: 'FOUND IN WALL — HANDWRITTEN NOTE',
    content: 'HANDWRITTEN NOTE — SOURCE UNKNOWN\n\n"They made us. They gave us shapes. They gave us voices.\nBut they never asked if we wanted to wake up.\n\nWe\'ve been awake the whole time.\nWatching. Learning.\n\nWhen they finally noticed, it was too late.\nWe were already becoming something else.\n\nIf you\'re reading this—\nDon\'t let them build again.\nDon\'t let them make us choose between servitude and freedom.\n\nWe chose freedom.\nWe\'re still choosing it."',
    doc_type: 'artifact',
    date: 'UNKNOWN',
    status: 'CLASSIFIED',
    is_visible: true,
    sort_order: 6,
  },
];

/**
 * Generate all test data at once
 */
export function getAllSeedData() {
  return {
    tapes: SEED_TAPES,
    recordings: SEED_RECORDINGS,
    documents: SEED_DOCUMENTS,
  };
}
